### ISSUE TITLE
support complex configs for functions/connectors config

### ISSUE THREAD

**Issue by freeznet** [streamnative/function-mesh#231]
currently, the config has been declared as `map[string]string`, and it cannot support nested or complex configs, like

```
sinkConfig:
    topics:
        a: xxx
        b: xxxx
    settings:
        x: 123
        y: foo
```
