### ISSUE TITLE
Service `function-mesh-controller-manager-metrics-service` has the wrong selector

### ISSUE THREAD

**Issue by EronWright** [streamnative/function-mesh#330]
Actual:
```
apiVersion: v1
kind: Service
metadata:
  name: function-mesh-controller-manager-metrics-service
  namespace: sn-system
spec:
  selector:
    control-plane: controller-manager
```

Expected:
```
spec:
  selector:
    control-plane: controller-manager
    app: function-mesh-operator
```
