### ISSUE TITLE
Support VPA

### ISSUE THREAD

**Issue by jiangpengcheng** [streamnative/function-mesh#462]

**Comment by jiangpengcheng** [comment]
Some notions about VPA:

1. It's applied to all containers of a pod, including sidecar containers(but not init containers)
2. it will keep the original ratio of `requests` and `limits`, for example

    the original resource definitions are:


    ```
    resources:
      requests:
        cpu: "0.1"
        memory: 1G
      limits:
        cpu: "0.2" // 2 times of the requests.cpu
        memory: 2G // 2 times of the requests.memory
    ```

    and the recommendation resources are:
    
    ```
    Target:
      Cpu:     100m
      Memory:  262144k
    ```

    then the generated resource for pod are:
    
    ```
    Limits:
      cpu:     200m // still keep 2 times of the requests.cpu
      memory:  524288k // still keep 2 times of the requests.memory
    Requests:
      cpu:     100m
      memory:  262144k
    ```
