### ISSUE TITLE
Q: Function download from external artifact repository after v0.5

### ISSUE THREAD

**Issue by MarkusNeuron** [streamnative/function-mesh#528]
Due to regulatory requirements we store all artefacts in a central registry. Therefore we configured the Function CR to download from the external URL:
```yaml
apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: exclamation-mark
spec:
  python:
    pyLocation: https://our-artefact-registry.corp/repository/1st-app-rel/neuron/application-neuron-playground/function/exclamationMark/67a3a0518462ac397ab33c1d68d9daf3c08448e3/exclamationMark-67a3a0518462ac397ab33c1d68d9daf3c08448e3.zip
    py: exclamationMark.zip
  ...
```
This mechanism stopped working after 0.5 by introducing the init-container and pulsarctl for download. Is there a way to still use the framework or do we need to introduce a custom init-container for external function download?
