### ISSUE TITLE
Function - SubscriptionName attribute ignored

### ISSUE THREAD

**Issue by relief-melone** [streamnative/function-mesh#562]
I currently have the problem that I want to set my subscription name to something else than the default. However even though the log in my function pod logs out that custom name on my pulsar the name of that subscription is still

[tenant]/[my-funcs-namespace]/[function_name]

Am I configuring it wrong or what could be the reason for this behaviour?

```yaml
apiVersion: compute.functionmesh.io/v1alpha1
kind: Function
metadata:
  name: my-func
spec:
  //....
  name: my-func
  tenant: tenant
  namespace: my-funcs-namespace
  subscriptionName: my-custom-sub-name
  //...
```
