### ISSUE TITLE
Ensure the Pod Security Standard follows `restricted` specification

### ISSUE THREAD

**Issue by nlu90** [streamnative/function-mesh#573]
1. Currently, the pod security context by default is:
```
securityContext:
     fsGroup: 1337
     runAsGroup: 10001
     runAsNonRoot: false
     runAsUser: 10000
```

The `runAsNonRoot` should be `true` by default or at least controlled by some ENV to allow people set in their cluster.

2. The pod security context also needs to set `securityContext.seccompProfile.type` to \"RuntimeDefault\" or \"Localhost\" 

4. some additions needed for the container security context:
```
securityContext.allowPrivilegeEscalation=false
securityContext.capabilities.drop=[\"ALL\"]
```
