### ISSUE TITLE
the `fsGroup` doesn't work if volume mount use an existing file/dir as subpath

### ISSUE THREAD

**Issue by jiangpengcheng** [streamnative/function-mesh#577]
example pod yaml using existing file:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-0
  namespace: default
spec:
  containers:
  - args:
    - while true; do sleep 30; done;
    command:
    - /bin/bash
    - -c
    - --
    image: streamnative/pulsar-functions-python-runner:2.10.0.0-rc10
    imagePullPolicy: IfNotPresent
    name: pulsar-function
    volumeMounts:
    - mountPath: /pulsar/pulsar_functions/exclamation.zip
      name: downloader-volume
      subPath: exclamation.zip
  hostname: test-0
  initContainers:
  - command:
    - sh
    - -c
    - wget http://nginx-server.default.svc.cluster.local/exclamation.zip -O /pulsar/download/exclamation.zip
    env:
    - name: HOME
      value: /tmp
    image: streamnative/pulsarctl:2.10.2.3
    imagePullPolicy: IfNotPresent
    name: downloader
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /pulsar/download
      name: downloader-volume
  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: false
    runAsUser: 10000
  volumes:
  - emptyDir: {}
    name: downloader-volume
```

another example using existing dir as subPath:

```
apiVersion: v1
kind: Pod
metadata:
  name: test-0
  namespace: default
spec:
  containers:
  - args:
    - while true; do sleep 30; done;
    command:
    - /bin/bash
    - -c
    - --
    image: streamnative/pulsar-functions-python-runner:2.10.0.0-rc10
    imagePullPolicy: IfNotPresent
    name: pulsar-function
    volumeMounts:
    - mountPath: /pulsar/pulsar_functions/temp
      name: downloader-volume
      subPath: temp
  hostname: test-0
  initContainers:
  - command:
    - sh
    - -c
    - mkdir /pulsar/download/temp
    env:
    - name: HOME
      value: /tmp
    image: streamnative/pulsarctl:2.10.2.3
    imagePullPolicy: IfNotPresent
    name: downloader
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /pulsar/download
      name: downloader-volume
  securityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: false
    runAsUser: 10000
  volumes:
  - emptyDir: {}
    name: downloader-volume
```

then the `/pulsar/download` directory is created with `root:root` permissions while the expected one is `root:pulsar`

This will made zip function file cannot be unzipped because of permission error
