### ISSUE TITLE
cannot get secret if the secret name has any dash

### ISSUE THREAD

**Issue by jiangpengcheng** [streamnative/function-mesh#712]
such as:

```yaml
  secretsMap:
    SEC-RET1:
      key: key1
      path: sec-name
```
