### ISSUE TITLE
java log config always using the `java_instance_log4j.xml` when the `java.Log.LogConfig` is set

### ISSUE THREAD

**Issue by jiangpengcheng** [streamnative/function-mesh#764]
for example, with below java log config:

```yaml
java:
  log:
    javaLog4JConfigFileType: yaml
    logConfig:
        key: log.yaml
        name: mylog
```

the correct way is to use `java_instance_log4j.yaml` as the `-Dpulsar.function.log.file`, but it still use the `java_instance_log4j.xml`
